[[entities]]
  entity = "minecraft:wither"
  minTier = 5
  maxTier = 5
  presetAffixes = ["arctic","paralyzing","molten","plagued","lively"]
  affixList = ["adaptable","dampening","shielding","wounding"]
  affixPermission = "BLACKLIST"
[[entities]]
  entity = "minecraft:ender_dragon"
  minTier = 5
  maxTier = 5
  presetAffixes = ["arctic","paralyzing","molten","hasty","wounding"]
  affixList = ["adaptable","dampening","shielding"]
  affixPermission = "BLACKLIST"
[[entities]]
  entity = "forestcraft:archaic_sentinel"
  minTier = 5
  maxTier = 5
  presetAffixes = ["arctic","paralyzing","molten","plagued","wounding"]
  affixList = ["adaptable","dampening","shielding"]
  affixPermission = "BLACKLIST"
[[entities]]
  entity = "forestcraft:iguana_king"
  minTier = 5
  maxTier = 5
  presetAffixes = ["arctic","paralyzing","molten","plagued","wounding"]
  affixList = ["adaptable","dampening","shielding"]
  affixPermission = "BLACKLIST"
[[entities]]
  entity = "forestcraft:beequeen"
  minTier = 5
  maxTier = 5
  presetAffixes = ["arctic","paralyzing","molten","plagued","wounding"]
  affixList = ["adaptable","dampening","shielding"]
  affixPermission = "BLACKLIST"
[[entities]]
  entity = "forestcraft:cosmic_fiend"
  minTier = 7
  maxTier = 7
  presetAffixes = ["arctic","paralyzing","molten","plagued","wounding","enkindling","reflective"]
  affixList = ["adaptable","dampening","shielding","magnetic","infextsd","knocking"]
  affixPermission = "BLACKLIST"
[[entities]]
  entity = "forestcraft:nether_scourge"
  minTier = 5
  maxTier = 5
  presetAffixes = ["enkindling","paralyzing","molten","plagued","wounding"]
  affixList = ["adaptable","dampening","shielding"]
  affixPermission = "BLACKLIST"
[[entities]]
  entity = "cataclysm:ender_guardian"
  minTier = 6
  maxTier = 6
  presetAffixes = ["arctic","paralyzing","molten","plagued","wounding"]
  affixList = ["adaptable","dampening","shielding"]
  affixPermission = "BLACKLIST"
[[entities]]
  entity = "cataclysm:netherite_monstrosity"
  minTier = 5
  maxTier = 5
  presetAffixes = ["enkindling","paralyzing","molten","plagued","wounding"]
  affixList = ["adaptable","dampening","shielding"]
  affixPermission = "BLACKLIST"
[[entities]]
  entity = "cataclysm:ignis"
  minTier = 6
  maxTier = 6
  presetAffixes = ["enkindling","paralyzing","molten","plagued","wounding"]
  affixList = ["adaptable","dampening","shielding"]
  affixPermission = "BLACKLIST"
[[entities]]
  entity = "meetyourfight:bellringer"
  minTier = 3
  maxTier = 3
  presetAffixes = ["molten","plagued","wounding"]
  affixList = ["adaptable","dampening","shielding"]
  affixPermission = "BLACKLIST"
[[entities]]
  entity = "meetyourfight:dame_fortuna"
  minTier = 3
  maxTier = 3
  presetAffixes = ["molten","plagued","wounding"]
  affixList = ["adaptable","dampening","shielding"]
  affixPermission = "BLACKLIST"
[[entities]]
  entity = "meetyourfight:swampjaw"
  minTier = 3
  maxTier = 3
  presetAffixes = ["molten","plagued","wounding"]
  affixList = ["adaptable","dampening","shielding"]
  affixPermission = "BLACKLIST"
