#Set to false to prevent Chromatic Arsenal from injecting its own items into loot chests. This will cause items only found in loot chests to become uncraftable.
lootTableInsertion = true

[CurioSettings]

	[CurioSettings.GoldenHeartSettings]
		#The max health granted when the player equips a golden heart.
		#Range: 4.9E-324 ~ 1.7976931348623157E308
		maxHealthBoost = 4.0
		#The operation used for the health bonus. 0 for additive, 1 for multiply base, 2 for multiply total.
		#Range: 0 ~ 2
		maxHealthBoostOperation = 0
		#The level of the absorption effect applied to the player while wearing the trinket. 0 is equivalent to effect level 1.
		#Range: 0 ~ 255
		absorptionLevel = 0
		#The duration of the absorption effect, in ticks. When this hits zero, the effect is re-applied.
		#Range: > 1
		absorptionDuration = 400
		#The extra max health gained per level of Protection on the Golden Heart. This obeys the operation, so if you set maxHealthBoostOperation to either 1 or 2, it's recommended to keep this at 0.1 at most.
		#Range: 4.9E-324 ~ 1.7976931348623157E308
		enchantmentMaxHealthIncrease = 1.0

	[CurioSettings.GlassShieldSettings]
		#The duration, in ticks, for the Glass Shield to recharge after it blocks a hit. Extremely low values effectively make you invincible. It is recommended to make this greater than enchantmentCooldownReduction, unless mending is unobtainable in your modpack.
		#Range: > 0
		cooldownDuration = 400
		#The amount of ticks to remove from the Glass Shield cooldown if Mending is applied. Note that if another mod changes Mending to have multiple levels, this will be multiplied by the level of the enchant.
		#Range: > 0
		enchantmentCooldownReduction = 100
		#The percent chance per level of Unbreaking to prevent the Glass Shield from shattering after blocking a hit. This is rounded up to the nearest whole number in-game. If your modpack has the ability to grant you outrageous levels of unbreaking, this should be set to a low value.
		#Range: 0.0 ~ 1.7976931348623157E308
		enchantmentFreeBlockChance = 2.0

	[CurioSettings.WardCrystalSettings]
		#The multiplier for incoming magic damage when wearing a Ward Crystal. 0.0 completely nullifies the attack, and 1.0 does not change the attack strength at all.
		#Range: 0.0 ~ 1.7976931348623157E308
		antiMagicMultiplierIncoming = 0.25
		#The multiplier for outgoing magic damage when wearing a Ward Crystal. 0.0 completely nullifies the attack, and 1.0 does not change the attack strength at all.
		#Range: 0.0 ~ 1.7976931348623157E308
		antiMagicMultiplierOutgoing = 0.25

	[CurioSettings.ShadowTreadsSettings]
		#The level of the speed effect applied to the player while in darkness. 0 is equivalent to effect level 1.
		#Range: 0 ~ 255
		darkspeedPotency = 0
		#The amount of passive speed granted by each level of Soul Speed.
		#Range: 4.9E-324 ~ 1.7976931348623157E308
		enchantmentSpeedMultiplier = 0.05

	[CurioSettings.DualityRingsSettings]
		#The damage multiplier of arrow projectiles while the Duality Rings are equipped. Values above 1.0 increase the damage, while values below 1.0 decrease the damage.
		#Range: 0.0 ~ 1.7976931348623157E308
		aroOfClubsMultiplier = 1.25
		#The level of the saturation effect applied to the player when consuming Magic Garlic Bread while the Duality Rings are equipped.
		#Range: 0 ~ 255
		saturationLevel = 0
		#The duration of the saturation effect, in ticks.
		#Range: > 1
		saturationDuration = 200
		#The level of the health boost effect applied to the player when consuming Magic Garlic Bread while the Duality Rings are equipped.
		#Range: 0 ~ 255
		healthBoostLevel = 2
		#The duration of the health boost effect, in ticks.
		#Range: > 1
		healthBoostDuration = 2400

	[CurioSettings.LunarCrystalSettings]
		#A 1 in X chance for an attacked entity to levitate upon being attacked while a Lunar Crystal is equipped.
		#Range: > 2
		levitationChance = 10
		#The duration of the Levitation effect, in ticks.
		#Range: > 1
		levitationDuration = 60
		#The level of the levitation effect. 0 is equivalent to effect level 1.
		#Range: 0 ~ 255
		levitationPotency = 2

[SuperCurioSettings]

	[SuperCurioSettings.SuperGoldenHeartSettings]
		#The duration of the Fractured effect, in ticks.
		#Range: > 1
		fracturedDuration = 6000
		#The level of the Fractured effect. Each level is 10% of max health lost.
		#Range: 0 ~ 255
		fracturedPotency = 4
		#The cooldown of the diamond heart before you are allowed to revive again. This is in ticks. Extremely low values effectively make you unable to die.
		#Range: > 0
		revivalCooldown = 6000

	[SuperCurioSettings.SuperGlassShieldSettings]
		#Once this amount of ticks is exceeded, the next fatal blow will kill the wearer.
		#Range: > 0
		revivalLimit = 3600
		#The amount of ticks added each time the Shield of Undying sustains a fatal blow. This stacks.
		#Range: > 0
		shatterRevivalCooldown = 1200
		#The operation 2 modifier given to the player wearing this shield. This should be negative or zero.
		#Range: -1.0 ~ 0.0
		healthTradeoff = -0.8

